# -- SWAP ETL default values

replicaCount: 2

image:
  repository: swap-ingestion-worker
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: swap-etl-worker
  automountServiceAccountToken: false

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 1Gi

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

networkPolicy:
  enabled: true

# -- MinIO subchart values
minio:
  enabled: false
  replicas: 4
  persistence:
    size: 50Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
